### PR TITLE
corrected the stderr var name

### PR DESCRIPTION
**Pull request by danielkoo**
just corrected the stderr name so it gets passed back in the callback

### CODE REVIEW

**Comment by danielkoo** [comment]
all good - thanks for the module btw :)

**Comment by hlfshell** [comment]
Hopefully you get some use out of it. I built it almost a year ago with
plans of automating some deploys at work but - as life tends to go - I
haven't been able to use it or touch it since :-(.

On Tue, May 19, 2015 at 9:39 PM, danielkoo notifications@github.com wrote:

> all good - thanks for the module btw :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hlfshell/node-packer/pull/1#issuecomment-103732536.

## 

~Keith

**Comment by hlfshell** [comment]
Found another bug in the builder - fixed. Check npm for 1.3. Trying to
build on digital ocean as a test now if I can squeeze it in ebfore bed.

On Tue, May 19, 2015 at 9:44 PM, Keith Chester kchester@gmail.com wrote:

> Hopefully you get some use out of it. I built it almost a year ago with
> plans of automating some deploys at work but - as life tends to go - I
> haven't been able to use it or touch it since :-(.
> 
> On Tue, May 19, 2015 at 9:39 PM, danielkoo notifications@github.com
> wrote:
> 
> > all good - thanks for the module btw :)
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/hlfshell/node-packer/pull/1#issuecomment-103732536.
> 
> ## 
> 
> ~Keith

## 

~Keith

**Comment by hlfshell** [comment]
OK - digital ocean v1 api is not supported by packer anymore - saw quite a
few raised issues on their github suggestings to upgrade to v2 as the fix.
SO I switched out the digital ocean builder to use the v2 api keys instead.
Check out version 0.1.2.

Did a successful image build using digital ocean which is all I have time
for tonight. Hope that helps!

On Tue, May 19, 2015 at 9:56 PM, Keith Chester kchester@gmail.com wrote:

> Found another bug in the builder - fixed. Check npm for 1.3. Trying to
> build on digital ocean as a test now if I can squeeze it in ebfore bed.
> 
> On Tue, May 19, 2015 at 9:44 PM, Keith Chester kchester@gmail.com wrote:
> 
> > Hopefully you get some use out of it. I built it almost a year ago with
> > plans of automating some deploys at work but - as life tends to go - I
> > haven't been able to use it or touch it since :-(.
> > 
> > On Tue, May 19, 2015 at 9:39 PM, danielkoo notifications@github.com
> > wrote:
> > 
> > > all good - thanks for the module btw :)
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/hlfshell/node-packer/pull/1#issuecomment-103732536.
> > 
> > ## 
> > 
> > ~Keith
> 
> ## 
> 
> ~Keith

## 

~Keith

**Comment by danielkoo** [comment]
Yes, we are using it and it seems to work fine for baking AWS AMIs :)

We are trying to coax more output out of the amazon-chroot builder, as by default it's quite opaque and doesn't help us pinpoint how it failed, when it does fail; not that this module has anything to do with that! If I could get Packer to be more verbose I will definitely see if we can turn it on from within this module. Cheers!

**Comment by hlfshell** [comment]
Alright then - I'll try to keep it maintained then since you're finding use
of it. I think I'm going to try and incorporate it into a docker-oriented
deploying module for work so this should see more love in the near future.
If packer does become more verbose (programmatically so) drop me a line and
I'll see about adding in the feature.

On Thu, May 21, 2015 at 6:48 PM, danielkoo notifications@github.com wrote:

> Yes, we are using it and it seems to work fine for baking AWS AMIs :)
> 
> We are trying to coax more output out of the amazon-chroot builder, as by
> default it's quite opaque and doesn't help us pinpoint how it failed, when
> it does fail; not that this module has anything to do with that! If I could
> get Packer to be more verbose I will definitely see if we can turn it on
> from within this module. Cheers!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hlfshell/node-packer/pull/1#issuecomment-104452190.

## 

~Keith

**Pull request merged**
